#!/bin/bash

# get script dir
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# read config file
source ./setupci.cfg

# check for a provided directory
if test -z "$1"; then
	echo "Please provide a directory name"
	exit
fi

# create directory if it doesn't exist
if [ ! -d $1 ]; then
	mkdir $1
fi

# move to directory
cd $1

# download codeigniter
curl -C - -L https://github.com/Estilingue/ECodeigniter/archive/master.zip -o ci.zip

# extract codeigniter
unzip ci.zip
mv ECodeigniter*/* .
rm -rf ECodeigniter* ci.zip

# find and remove all the index.html files
find . -name 'index.html' -exec rm -f {} \;

# remove the base .htaccess from template
rm -rf .htaccess

# copy over .htaccess
cp $DIR/templates/.htaccess .

# set permissions on cache and log folder
chmod 755 application/cache application/logs

# check if we should skip git
if [ "$2" != "--no-git" ]; then

	# copy over .gitignore
	cp $DIR/templates/.gitignore .

	# create a local git repo
	git init
	git add * .gitignore
	git commit -m "Initial commit."

fi

# get a md5sum of the date command
MD5=`date | openssl md5`

# provide instructions
echo ""
echo ""
echo ""
echo "========================================================================"
echo "Remaining steps:"
echo " 1. In 'application/config/config.php' add the base_url and an"
echo "    encryption_key value ($MD5)"
echo ""
echo " 2. In 'application/config/database.php' add database credentials"
echo ""
echo "========================================================================"
echo ""
